### Cadastrar Usuário / Conta
POST  http://localhost:3000/user/ HTTP/1.1
content-type: application/json
{
  "name": "Jorge",
  "email": "jorge@igiveup.com"
}

### Alterar Usuário / Conta
PUT http://localhost:3000/user/ HTTP/1.1
content-type: application/json
{
  "name": "Jonas",
  "email": "jonasbrother@igiveup.com"
}

### Deletar Usuário / Conta
DELETE http://localhost:3000/user

### Usuário
GET http://localhost:3000/user/

### Cadastrar o Depósito
PUT http://localhost:3000/user/deposit/
content-type: application/json
{

}
### Cadastrar a Retirada
PUT http://localhost:3000/user/withdraw/

### Extrato da conta
GET http://localhost:3000/user/extract/

### Saldo da conta
GET http://localhost:3000/user/balance/
