### Todos os IDs
GET http://localhost:3000/user/

### Extrato e saldo do usuário
GET http://localhost:3000/user/757e59ad-ddbd-4ee6-9102-97944678cbc6

### Cadastrar Usuário
POST http://localhost:3000/user/
content-type: application/json

{
    "name": "Dionatan",
    "cpf":"123.456.420-00",
    "cep":"98780080",
    "cidade":"Santa Rosa",
    "saldo": 0,
    "transacao": []

}

### Depositar na conta do usuário
PUT  http://localhost:3000/user/deposito/757e59ad-ddbd-4ee6-9102-97944678cbc6
content-type: application/json

{
    "tipo": "deposito",
    "valor": 100

}

### Retirar da conta do usuário
PUT  http://localhost:3000/user/retirada/757e59ad-ddbd-4ee6-9102-97944678cbc6
content-type: application/json

{

    "tipo": "retirada",
    "valor": 50

}

### Deletar usuário
DELETE http://localhost:3000/user/757e59ad-ddbd-4ee6-9102-97944678cbc6

### Atualizar um usuario pelo ID
PUT  http://localhost:3000/user/f3614955-80b8-4a2b-969b-9750780efcfe
content-type: application/json

{
    "name": "Lucas",
    "cpf":"123.456.420-00",
    "cep":"98780080",
    "cidade":"Santa Rosa"
}
